export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER        = 'LOGOUT_USER';
export const GET_PRODUCT_KEY_VALUES = 'GET_PRODUCT_KEY_VALUES';

export const SIGNUP_SUCCESS     = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED      = 'SIGNUP_FAILED';
export const SIGNUP_REQUEST      = 'SIGNUP_REQUEST';
export const SHOW_FLOATING_NOTIFICATION = "SHOW_FLOATING_NOTIFICATION";
export const HIDE_FLOATING_NOTIFICATION = "HIDE_FLOATING_NOTIFICATION";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const LOGOUT = 'LOGOUT';
export const RESTORE_LOGIN = 'RESTORE_LOGIN';

export const FETCH_ORDERS_LIMIT = 2;
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const SET_SEARCH_SPECS  = 'SET_SEARCH_SPECS';
export const TOGGLE_ORDER_SELECTED = 'TOGGLE_ORDER_SELECTED';

export const SET_CASCADED_TAB_VISIBILITY = 'SET_CASCADED_TAB_VISIBILITY';
